import { StrictMode, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ChevronLeft, ChevronRight, Menu, MoveUpRight, Quote, Star, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import { useInViewAnimation } from './hooks/useInViewAnimation';
import './styles.css';
import './cinematic-mobile.css';

const gallery = [
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1512621776951-a57141f2e0a7?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1505576633757-0ac1084af824?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1512621776951-a57141f2e0a7?auto=format&fit=crop&w=1000&q=85',
];
const testimonials = [
  ['Участница марафона', 'Результат требует подтверждения', 'За время программы минус 6 кг и это без голода! Наталья всегда на связи, поддерживает и мотивирует в самые сложные моменты.', 'М'],
  ['Участница марафона', 'Результат требует подтверждения', 'Я уже пробовала кучу диет, но здесь совсем другой подход. Ментор реально помогает и ты не бросаешь на полпути.', 'А'],
  ['Участница марафона', 'Результат требует подтверждения', 'Это не просто диета — это образ жизни. После марафона стало намного понятнее, как собирать рацион и не возвращаться к хаосу.', 'Е'],
  ['Участница марафона', 'Результат требует подтверждения', 'Программа прошла на одном дыхании! Наталья каждый день на связи, всегда ответит и поддержит.', 'О'],
  ['Участница марафона', 'Результат требует подтверждения', 'Никогда не думала, что смогу похудеть без жёстких ограничений. Меню вкусное, а поддержка помогает держать темп.', 'И'],
];
const stages = [
  ['Мягкий старт', 'Наводим порядок в рационе, знакомимся с меню и выстраиваем режим без резких ограничений.', 'Антивоспалительное меню · Простые рецепты · Утренние чек-ины'],
  ['Рабочий ритм', 'Следуем персональному рациону, наблюдаем динамику и разбираем моменты, которые мешают придерживаться плана.', 'Индивидуальный рацион · Контроль порций и КБЖУ · Ежедневные отчёты'],
  ['Поддержание', 'Расширяем рацион и переносим новые привычки в обычную жизнь без обещаний гарантированного результата.', 'Сбалансированное питание · Навыки на всю жизнь · Финальные итоги'],
];
const GOOGLE_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbzRC5ecCQjBHqfLDxxAUAxqiXRTfRDAz71qEyGXNa5aUwCYxs7prjCTc1CBCWtOEIRf/exec';

function Reveal({ children, className = '', delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  const animation = useInViewAnimation();
  return <div ref={animation.ref} className={`${animation.className} ${className}`} style={{ animationDelay: `${delay}s` }}>{children}</div>;
}
function ParallaxImage() {
  const ref = useRef<HTMLDivElement>(null); const frame = useRef(0); const [offset, setOffset] = useState(0); const [active, setActive] = useState(false);
  useEffect(() => { if (!ref.current) return; const observer = new IntersectionObserver(([entry]) => setActive(entry.isIntersecting), { threshold: .1 }); observer.observe(ref.current); return () => observer.disconnect(); }, []);
  useEffect(() => { const onScroll = () => { cancelAnimationFrame(frame.current); frame.current = requestAnimationFrame(() => { if (active && ref.current) { const r = ref.current.getBoundingClientRect(); setOffset(Math.max(-200, Math.min(200, (innerHeight / 2 - r.top) * .2))); } }); }; addEventListener('scroll', onScroll, { passive: true }); onScroll(); return () => { cancelAnimationFrame(frame.current); removeEventListener('scroll', onScroll); }; }, [active]);
  return <div ref={ref} className="parallax-frame"><img src="https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1000&q=85" alt="Наталья готовит полезное блюдо" style={{ transform: `translateY(${offset}px) scale(1.08)` }} /></div>;
}
function CinematicHero() {
  const videoRef = useRef<HTMLVideoElement>(null); const frame = useRef(0); const current = useRef({ x: 0, y: 0 }); const target = useRef({ x: 0, y: 0 });
  useEffect(() => { const onMove = (event: MouseEvent) => { target.current.x = ((event.clientX - innerWidth / 2) / (innerWidth / 2)) * 18; target.current.y = ((event.clientY - innerHeight / 2) / (innerHeight / 2)) * 12; }; const loop = () => { current.current.x += (target.current.x - current.current.x) * .06; current.current.y += (target.current.y - current.current.y) * .06; if (videoRef.current) videoRef.current.style.transform = `translate3d(${current.current.x}px, ${current.current.y}px, 0) scale(1.08)`; frame.current = requestAnimationFrame(loop); }; addEventListener('mousemove', onMove, { passive: true }); frame.current = requestAnimationFrame(loop); return () => { removeEventListener('mousemove', onMove); cancelAnimationFrame(frame.current); }; }, []);
  return <section id="top" className="cinematic-hero"><video ref={videoRef} className="cinematic-video" autoPlay muted loop playsInline preload="auto" onLoadedMetadata={(event) => { event.currentTarget.playbackRate = 1.25; }}><source src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260510_060007_60275ce7-030c-4668-a160-8f364ec537d3.mp4" type="video/mp4" /></video><div className="cinematic-shade" /><div className="cinematic-copy"><Reveal delay={.1}><p className="cinematic-kicker">Марафон «Сильные девочки» · SmartSlimWay</p></Reveal><Reveal delay={.2}><h1>Питание<br /><em>без крайностей.</em></h1></Reveal><Reveal delay={.3}><p className="cinematic-description">Собери свою систему питания — в своём ритме, с поддержкой и без вечной войны с собой.</p></Reveal><Reveal delay={.4}><a className="cinematic-cta" href="/application">Подать заявку <ArrowUpRight size={16} /></a></Reveal></div><div className="cinematic-bottom"><span>Три этапа · Личный ментор · Онлайн-анкета</span><span className="cinematic-scroll">Scroll to explore ↓</span></div></section>;
}
function Reviews() {
  const [active, setActive] = useState(0); const [paused, setPaused] = useState(false);
  useEffect(() => { if (paused) return; const timer = setInterval(() => setActive((x) => (x + 1) % testimonials.length), 3000); return () => clearInterval(timer); }, [paused]);
  const move = (direction: number) => setActive((x) => (x + direction + testimonials.length) % testimonials.length);
  return <section className="reviews" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}><div className="wide review-head"><h2>Что говорят <em>участницы</em></h2><div className="rating"><span>{[1, 2, 3, 4, 5].map((n) => <Star key={n} size={18} fill="currentColor" />)}</span> Поддержка каждый день</div></div><div className="review-window"><div className="review-track" style={{ transform: `translateX(calc(-${active} * (min(427.5px, calc(100vw - 48px)) + 24px)))` }}>{[...testimonials, ...testimonials, ...testimonials].map((item, i) => <article className="review-card" key={`${item[0]}-${i}`}><Quote size={26} strokeWidth={1.2} /><p>«{item[2]}»</p><div className="author"><div className="review-avatar">{item[3]}</div><div><strong>{item[0]}</strong><small>↳ {item[1]}</small></div></div></article>)}</div></div><div className="review-controls"><button onClick={() => move(-1)} aria-label="Предыдущий отзыв"><ChevronLeft size={19} /></button><button onClick={() => move(1)} aria-label="Следующий отзыв"><ChevronRight size={19} /></button></div></section>;
}
function Partner() {
  const [thumbs, setThumbs] = useState<{ id: number; src: string; x: number; y: number; rotate: number }[]>([]); const lastSpawn = useRef(0); const cleanupFrame = useRef(0);
  useEffect(() => () => cancelAnimationFrame(cleanupFrame.current), []);
  const addThumb = (e: React.MouseEvent<HTMLDivElement>) => { const now = performance.now(); if (now - lastSpawn.current < 80) return; lastSpawn.current = now; const box = e.currentTarget.getBoundingClientRect(); const id = Date.now(); setThumbs((all) => [...all.slice(-7), { id, src: gallery[Math.floor(Math.random() * gallery.length)], x: e.clientX - box.left, y: e.clientY - box.top, rotate: Math.random() * 20 - 10 }]); cleanupFrame.current = requestAnimationFrame(() => setTimeout(() => setThumbs((all) => all.filter((t) => t.id !== id)), 1000)); };
  return <section className="partner wide" onMouseMove={addThumb}><div className="partner-inner"><h2>Начать <em>свой путь</em></h2><a className="button primary partner-button" href="#application"><span className="partner-letter">Н</span>Подать заявку на марафон <ArrowUpRight size={15} /></a>{thumbs.map((t) => <img className="cursor-thumb" key={t.id} src={t.src} alt="" style={{ left: t.x, top: t.y, transform: `translate(-50%, -50%) rotate(${t.rotate}deg)` }} />)}</div></section>;
}
function Footer() { return <><footer className="site-footer wide"><a className="button primary" href="/application">Подать заявку <MoveUpRight size={16} /></a><div className="footer-links"><ArrowUpRight size={18} /><div><a href="/program">Программа</a><a href="/reviews">Отзывы</a><a href="/about">О Наталье</a></div><div><a href="/application">Анкета</a><a href="/contacts">Контакты</a></div></div></footer><div className="copyright wide"><span>Умный путь к стройности</span><span>Онлайн-заявка на марафон</span></div></>; }
function ApplicationForm() {
  const [status, setStatus] = useState(''); const [sending, setSending] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSending(true); setStatus('Отправляю анкету...'); const form = new FormData(event.currentTarget); const telegram = String(form.get('telegram') || '').trim().replace(/^@/, ''); const data = { createdAt: new Date().toISOString(), program: 'Сильные девочки', price: '6000', source: 'smartslimway-site', name: form.get('name') || '', phone: form.get('phone') || '', telegram, email: form.get('email') || '', age: form.get('age') || '', weight: form.get('weight') || '', goal: form.get('goal') || '', experience: form.get('experience') || '', motivation: form.get('motivation') || '' }; try { const saved = JSON.parse(localStorage.getItem('smart-path-applications') || '[]'); localStorage.setItem('smart-path-applications', JSON.stringify([...saved, data])); const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 8000); const response = await fetch(GOOGLE_SCRIPT_URL, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify(data), signal: controller.signal }); window.clearTimeout(timeout); if (!response.ok) throw new Error('sheet'); setStatus('Анкета отправлена. Наталья свяжется с тобой лично.'); event.currentTarget.reset(); } catch { setStatus('Анкета сохранена локально. Проверь подключение к таблице и повтори отправку.'); } finally { setSending(false); } };
  return <form className="application-form" onSubmit={submit}><div className="form-grid"><label>Имя *<input name="name" required placeholder="Твоё имя" /></label><label>Телефон *<input name="phone" type="tel" required placeholder="+7 (999) 123-45-67" /></label><label>Telegram<input name="telegram" placeholder="@username" /></label><label>Email *<input name="email" type="email" required placeholder="твой@email.com" /></label><label>Возраст<input name="age" type="number" min="16" max="99" placeholder="25" /></label><label>Текущий вес<input name="weight" placeholder="65 кг" /></label></div><label>Цель *<input name="goal" required placeholder="Например: наладить режим питания" /></label><fieldset><legend>Опыт с диетами</legend><label><input type="radio" name="experience" value="Новичок" /> Новичок</label><label><input type="radio" name="experience" value="Есть опыт" /> Есть опыт</label><label><input type="radio" name="experience" value="Пробовала много" /> Пробовала много</label></fieldset><label>Почему хочешь участвовать?<textarea name="motivation" rows={4} placeholder="Расскажи о своей ситуации..." /></label><label className="consent"><input type="checkbox" required /> Согласна на обработку персональных данных</label><button className="button primary" type="submit" disabled={sending}>{sending ? 'Отправляю...' : 'Отправить анкету'} <ArrowUpRight size={16} /></button><p className="form-status" role="status">{status}</p></form>;
}
function PageNav({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  useEffect(() => { const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setOpen(false); addEventListener('keydown', onKey); return () => removeEventListener('keydown', onKey); }, []);
  const links = [['/about', 'О Наталье'], ['/program', 'Программа'], ['/reviews', 'Результаты'], ['/faq', 'FAQ'], ['/contacts', 'Контакты']];
  return <main><header className="topbar"><a className="mini-logo" href="/">SSW<span>.</span></a><span className="top-note">Марафон «Сильные девочки» / 2026</span><div className="top-actions"><a className="nav-link" href="/application">Рассчитать калории <ArrowUpRight size={14} /></a><button className="menu-trigger" type="button" onClick={() => setOpen(true)} aria-label="Открыть меню"><Menu size={23} strokeWidth={1.5} /></button></div></header><div className={`menu-overlay ${open ? 'is-open' : ''}`} onClick={() => setOpen(false)} /><aside className={`menu-drawer ${open ? 'is-open' : ''}`} aria-hidden={!open}><button className="menu-close" type="button" onClick={() => setOpen(false)} aria-label="Закрыть меню"><X size={23} /></button><p className="eyebrow">Умный путь к стройности</p><p className="drawer-title">Выбери свой<br /><em>следующий шаг.</em></p><nav className="drawer-links">{links.map(([href, label], i) => <a key={href} href={href} onClick={() => setOpen(false)}><span>0{i + 1}</span>{label}<ArrowUpRight size={15} /></a>)}</nav><a className="button primary drawer-cta" href="/application">Подать заявку <MoveUpRight size={16} /></a></aside>{children}<Footer /><nav className="bottom-nav" aria-label="Быстрая заявка"><span>SSW</span><a className="button primary" href="/application">Подать заявку <ArrowUpRight size={14} /></a></nav></main>;
}
function InnerPage({ path }: { path: string }) {
  const data: Record<string, { kicker: string; title: React.ReactNode; copy: string }> = {
    '/about': { kicker: 'Наталья · нутрициолог и ментор', title: <>Питание, которое<br /><em>встраивается в жизнь.</em></>, copy: 'Я помогаю выстроить понятный рацион, который учитывает твою цель, привычки и реальный распорядок дня.' },
    '/program': { kicker: 'Марафон «Сильные девочки»', title: <>Три этапа к<br /><em>своей системе.</em></>, copy: 'Персональное меню, ежедневная обратная связь и поддержка без голодовок, чувства вины и жёстких запретов.' },
    '/reviews': { kicker: 'Опыт участниц', title: <>Результат начинается<br /><em>с поддержки.</em></>, copy: 'Здесь собраны истории участниц. Реальные отзывы и скриншоты публикуются только с согласия и после подтверждения.' },
    '/faq': { kicker: 'Вопросы перед стартом', title: <>Разобраться<br /><em>спокойно.</em></>, copy: 'Ответы на главные вопросы о формате, меню, сопровождении и стоимости марафона.' },
    '/contacts': { kicker: 'Связаться напрямую', title: <>Готова начать<br /><em>свой путь?</em></>, copy: 'Наталья ответит лично, расскажет детали программы и поможет сделать первый шаг без стресса.' },
    '/application': { kicker: 'Анкета на участие', title: <>Перед стартом<br /><em>познакомимся.</em></>, copy: 'Заполни анкету — она попадёт в онлайн-таблицу, а Наталья свяжется с тобой лично и ответит на вопросы о марафоне.' },
  };
  const current = data[path] || data['/about'];
  return <PageNav><section className="inner-hero wide"><Reveal><p className="eyebrow">{current.kicker}</p><h1>{current.title}</h1><p>{current.copy}</p>{path !== '/application' && <a className="button primary" href="/application">Подать заявку <ArrowUpRight size={16} /></a>}</Reveal></section>{path === '/about' && <AboutContent />}{path === '/program' && <ProgramContent />}{path === '/reviews' && <ReviewsContent />}{path === '/faq' && <FaqContent />}{path === '/application' && <section className="inner-content wide"><div className="application-layout"><div className="application-intro"><p className="eyebrow">Марафон «Сильные девочки»</p><h2>Заявка на<br /><em>участие.</em></h2><p>Стоимость программы — <strong>6 000 ₽</strong>.</p><ul><li>Индивидуальное меню</li><li>Личный ментор каждый день</li><li>Групповой чат и полезные материалы</li></ul></div><ApplicationForm /></div></section>}{path === '/contacts' && <ContactContent application={false} />}</PageNav>;
}
function AboutContent() { return <section className="inner-content wide"><div className="inner-split"><div><p className="eyebrow">Наталья</p><h2>Нутрициолог<br /><em>и ментор.</em></h2></div><div><p>Я — Наталья, нутрициолог и создатель марафона «Сильные девочки». Я знаю, как это — когда кажется, что ничего не работает.</p><p>Моя методика основана на мягком, но системном подходе. Никаких голодовок и волшебных таблеток — только питание, поддержка и шаг за шагом к результату.</p><div className="fact-row"><span>1 : 1<small>личная обратная связь</small></span><span>3<small>этапа программы</small></span><span>+ support<small>продолжение отдельно</small></span></div></div></div><img className="inner-image" src={gallery[1]} alt="Полезное блюдо на кухне" /></section>; }
function ProgramContent() { return <section className="inner-content wide"><div className="inner-section-title"><p className="eyebrow">Что входит</p><h2>Понятный маршрут<br /><em>без крайностей.</em></h2></div><div className="inner-stage-grid">{stages.map((stage, i) => <article className={i === 1 ? 'dark-plan' : ''} key={stage[0]}><span>Этап 0{i + 1}</span><h3>{stage[0]}</h3><p>{stage[1]}</p><strong>{stage[2]}</strong></article>)}</div><div className="price-strip"><span>Марафон «Сильные девочки»</span><strong>6 000 ₽</strong><a className="button primary" href="/application">Подать заявку <ArrowUpRight size={15} /></a></div></section>; }
function ReviewsContent() { return <section className="inner-content wide"><div className="review-grid-static">{testimonials.map((item) => <article className="review-card" key={item[3]}><Quote size={24} /><p>«{item[2]}»</p><div className="author"><div className="review-avatar">{item[3]}</div><div><strong>{item[0]}</strong><small>{item[1]}</small></div></div></article>)}</div><p className="pending-note">Имена и результаты требуют подтверждения участниц перед публикацией.</p></section>; }
function FaqContent() { return <section className="inner-content wide"><div className="faq-grid full-faq"><details open><summary>Как проходит марафон? <ArrowUpRight size={16} /></summary><p>Сначала разбираемся с текущим рационом, затем собираем меню под твою цель и каждый день остаёмся на связи через отчёты и обратную связь.</p></details><details><summary>Нужно ли считать калории? <ArrowUpRight size={16} /></summary><p>Контроль порций и КБЖУ входит в рабочий этап, но задача — научиться понимать питание, а не жить в постоянных ограничениях.</p></details><details><summary>Что входит в стоимость? <ArrowUpRight size={16} /></summary><p>Индивидуальное меню, личный ментор, ежедневная обратная связь, групповой чат, полезные материалы и рецепты.</p></details></div></section>; }
function ContactContent({ application }: { application: boolean }) { return <section className="inner-content wide"><div className="contact-card"><p className="eyebrow">{application ? 'Марафон «Сильные девочки»' : 'Онлайн-анкета'}</p><h2>{application ? 'Оставь заявку<br /><em>на участие.</em>' : 'Задать вопрос<br /><em>через анкету.</em>'}</h2><p>Заполни анкету, и Наталья получит заявку в онлайн-таблице. После этого она свяжется с тобой лично.</p><a className="button primary" href="/application">Заполнить анкету <ArrowUpRight size={16} /></a></div></section>; }
function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setMenuOpen(false); }; addEventListener('keydown', onKey); return () => removeEventListener('keydown', onKey); }, []);
  const closeMenu = () => setMenuOpen(false);
  return <main><header className="topbar"><a className="mini-logo" href="/">SSW<span>.</span></a><span className="top-note">Марафон «Сильные девочки» / 2026</span><div className="top-actions"><a className="nav-link" href="/application">Рассчитать калории <ArrowUpRight size={14} /></a><button className="menu-trigger" type="button" onClick={() => setMenuOpen(true)} aria-label="Открыть меню" aria-expanded={menuOpen}><Menu size={23} strokeWidth={1.5} /></button></div></header>
    <div className={`menu-overlay ${menuOpen ? 'is-open' : ''}`} onClick={closeMenu} aria-hidden="true" />
    <aside className={`menu-drawer ${menuOpen ? 'is-open' : ''}`} aria-label="Навигация по сайту" aria-hidden={!menuOpen}><button className="menu-close" type="button" onClick={closeMenu} aria-label="Закрыть меню"><X size={23} /></button><p className="eyebrow">Умный путь к стройности</p><p className="drawer-title">Выбери свой<br /><em>следующий шаг.</em></p><nav className="drawer-links"><a href="/about" onClick={closeMenu}><span>01</span>О Наталье <ArrowUpRight size={15} /></a><a href="/program" onClick={closeMenu}><span>02</span>Программа <ArrowUpRight size={15} /></a><a href="/reviews" onClick={closeMenu}><span>03</span>Результаты <ArrowUpRight size={15} /></a><a href="/faq" onClick={closeMenu}><span>04</span>FAQ <ArrowUpRight size={15} /></a><a href="/contacts" onClick={closeMenu}><span>05</span>Контакты <ArrowUpRight size={15} /></a></nav><a className="button primary drawer-cta" href="/application" onClick={closeMenu}>Подать заявку <MoveUpRight size={16} /></a></aside>
    <CinematicHero /><section className="hero page-column editorial-intro"><Reveal delay={.1}><div className="logo">Умный путь<br />к стройности</div></Reveal><Reveal delay={.2}><div className="eyebrow">Персональная программа питания</div></Reveal><Reveal delay={.3}><h2>Есть вкусно.<br />Чувствовать<br /><em>лёгкость.</em></h2></Reveal><Reveal delay={.4} className="intro"><p>Персональный рацион и спокойное сопровождение — без голодовок, чувства вины и попыток начать новую жизнь каждый понедельник.</p><p>Наталья рядом каждый день: смотрит отчёты, отвечает на вопросы и помогает выстроить питание под твою настоящую жизнь.</p><p className="price">Участие в марафоне — <strong>6 000 ₽</strong>.</p></Reveal><Reveal delay={.5} className="hero-actions"><a className="button primary" href="/application">Подать заявку <MoveUpRight size={16} /></a><a className="button secondary" href="#program">Как это работает <ArrowUpRight size={16} /></a></Reveal></section>
    <section id="work" className="marquee-wrap" aria-label="Питание и забота о себе"><div className="marquee-track">{[...gallery, ...gallery].map((src, i) => <img key={`${src}-${i}`} src={src} alt="Питание, движение и забота о себе" loading={i > 3 ? 'lazy' : 'eager'} />)}</div></section>
    <section id="about" className="quote-section page-column"><Reveal delay={.1}><Quote size={25} strokeWidth={1.5} /></Reveal><Reveal delay={.2}><blockquote>«Ты не ленивая. Ты просто устала от правил, которые невозможно встроить в жизнь».</blockquote></Reveal><Reveal delay={.3}><cite>— Наталья, нутрициолог и ментор</cite></Reveal><Reveal delay={.4} className="logos"><span>1 : 1</span><span>3 этапа</span><span>+ support</span></Reveal><Reveal delay={.5}><ParallaxImage /></Reveal></section>
    <section id="program" className="pricing wide"><Reveal className="pricing-title"><p className="eyebrow">Как строится программа</p><h2>Питание без войны<br /><em>с собой.</em></h2></Reveal><div className="pricing-grid">{stages.map((stage, i) => <Reveal key={stage[0]} delay={i * .1}><article className={`plan ${i === 1 ? 'dark-plan' : 'light-plan'} stage-plan`}><span className="stage-number">Этап 0{i + 1}</span><h3>{stage[0]}</h3><p>{stage[1]}</p><strong>{stage[2]}</strong></article></Reveal>)}</div></section>
    <section id="reviews"><Reviews /></section>
    <section className="case-studies wide"><Reveal><p className="eyebrow">Что входит в марафон</p><h2>Система, которая<br /><em>остаётся с тобой.</em></h2></Reveal><div className="case-list">{[['Индивидуальное меню', 'Рацион на каждый день под твою цель и привычки', gallery[1]], ['Ежедневная связь', 'Личный ментор, отчёты, обратная связь и групповой чат', gallery[2]], ['Навыки на всю жизнь', 'Рецепты и понятная система без вечных запретов', gallery[5]]].map((item, i) => <Reveal key={item[0]} delay={i * .1}><article className="case-item"><div className="case-label"><h3>{item[0]}</h3><p>{item[1]}</p></div><img src={item[2]} alt={item[0]} loading="lazy" /></article></Reveal>)}</div></section>
    <Partner /><section id="application" className="manifesto"><div className="manifesto-inner"><Reveal><p className="eyebrow light">Марафон «Сильные девочки»</p><h2>Первый шаг —<br /><em>оставить заявку.</em></h2></Reveal><Reveal delay={.2} className="manifesto-copy"><p>После заявки Наталья свяжется с тобой лично, расскажет детали участия и поможет понять, подходит ли тебе такой формат.</p><a className="text-link" href="/application">Заполнить анкету <ArrowUpRight size={15} /></a></Reveal></div></section>
    <section id="faq" className="faq wide"><Reveal><p className="eyebrow">04 / вопросы</p><h2>Спокойно разобраться<br /><em>перед стартом.</em></h2></Reveal><div className="faq-grid"><details><summary>Как проходит марафон? <ArrowUpRight size={16} /></summary><p>Сначала разбираемся с текущим рационом, затем собираем меню под твою цель и каждый день остаёмся на связи через отчёты и обратную связь.</p></details><details><summary>Нужно ли считать калории? <ArrowUpRight size={16} /></summary><p>Контроль порций и КБЖУ входит в рабочий этап программы, но задача марафона — научиться понимать питание, а не жить в постоянных ограничениях.</p></details><details><summary>Что входит в стоимость? <ArrowUpRight size={16} /></summary><p>Индивидуальное меню, личный ментор, ежедневная обратная связь, групповой чат, полезные материалы и рецепты.</p></details></div></section>
    <section id="calories" className="calorie-band"><div className="calorie-inner wide"><div><p className="eyebrow light">Быстрый первый шаг</p><h2>Понять свою<br /><em>точку старта.</em></h2></div><a className="button light-button" href="#application">Рассчитать калории <ArrowUpRight size={16} /></a></div></section>
    <section id="contacts" className="contact page-column"><Reveal><div className="eyebrow">Готова начать?</div><h2>Соберём<br /><em>твою систему.</em></h2></Reveal><a className="contact-submit" href="/application">Заполнить анкету на участие <ArrowUpRight size={17} /></a><footer><span>Умный путь к стройности © 2026</span><span>Информация не заменяет консультацию врача</span><a href="#top">Наверх ↑</a></footer></section><Footer /><nav className="bottom-nav" aria-label="Быстрая заявка"><span>SSW</span><a className="button primary" href="#application">Подать заявку <ArrowUpRight size={14} /></a></nav>
  </main>;
}
const path = window.location.pathname.replace(/\/$/, '') || '/';
createRoot(document.getElementById('root')!).render(<StrictMode>{path === '/' ? <App /> : <InnerPage path={path} />}</StrictMode>);
